version: '3'
services:
  postgres:
    image: 'postgres:10'
  redis:
    image: 'redis:4'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app